# 文档过滤规则配置文件
# 支持多种过滤方式：文档类型、关键词、正则表达式、文件属性等

# 过滤模式
filter_mode:
  # mode 可选值：
  # - "whitelist" (白名单模式：只处理匹配的类型)
  # - "blacklist" (黑名单模式：跳过匹配的类型)
  # - "hybrid" (混合模式：白名单优先，然后应用黑名单)
  mode: "hybrid"

# 文档类型过滤（基于我们扩展的16种文档类型）
document_types:
  # 白名单：只处理这些文档类型
  whitelist:
    - "rights"          # 供股
    - "placing"         # 配售
    - "ipo"             # IPO
    - "consolidation"   # 合股/拆股
    - "split"           # 拆股
    - "acquisition"     # 收购
    - "disposal"        # 出售
    - "disclosable_transaction"  # 须予披露交易
    - "connected_transaction"    # 关连交易
    - "very_substantial_acquisition"  # 非常重大收购
    - "very_substantial_disposal"     # 非常重大出售
    - "share_option"    # 购股权计划
    - "dividend"        # 股息分派
    - "capital_reduction"  # 股本缩减
    - "share_repurchase"   # 股份回购

  # 黑名单：跳过这些文档类型
  blacklist:
    # 例如：如果不想处理股息分派，可以在这里添加
    # - "dividend"

  # 默认处理策略：未明确指定类型的文档如何处理
  # 可选值："process" (处理), "skip" (跳过)
  default_action: "skip"

# 关键词过滤
keyword_filters:
  # 黑名单关键词（包含这些关键词的文档会被跳过）
  blacklist:
    # 定期报告类
    - "月报表"
    - "月報表"
    - "季报"
    - "季報"
    - "半年报"
    - "半年報"
    - "年报"
    - "年報"
    - "环境、社会及管治"
    - "环境社会管治"
    - "ESG"

    # 会议通知类
    - "股东大会通告"
    - "股東大會通告"
    - "股东周年大会"
    - "股東週年大會"
    - "股东特别大会"
    - "股東特別大會"
    - "通告"
    - "通知"
    - "委任代表表格"
    - "代表委任表格"

    # 管理性文件
    - "展示文件"
    - "展示档案"
    - "送呈"
    - "送交"
    - "更改"
    - "更换"
    - "更換"
    - "变更"
    - "變更"

    # 日常运营类
    - "董事会会议"
    - "董事會會議"
    - "董事名单"
    - "董事名單"
    - "业务发展最新情况"
    - "業務發展最新情況"

    # 表格类
    - "月份之股份发行人的证券变动月报表"
    - "證券變動月報表"

    # 其他杂项
    - "盈利警告"
    - "盈警"
    - "暂停办理过户登记手续"
    - "暫停辦理過戶"

  # 白名单关键词（包含这些关键词的文档会被优先处理）
  whitelist:
    - "供股"
    - "配售"
    - "IPO"
    - "招股"
    - "上市"
    - "合股"
    - "股本整合"
    - "收购"
    - "收購"
    - "出售"
    - "處置"
    - "须予披露交易"
    - "須予披露交易"
    - "关连交易"
    - "關連交易"
    - "非常重大出售"
    - "非常重大收购"

  # 是否启用关键词过滤
  enabled: true

# 正则表达式模式过滤
pattern_filters:
  # 黑名单模式（匹配这些正则模式的文档会被跳过）
  blacklist_patterns:
    # 月报表模式
    - '^\d{4}-\d{2}-\d{2}_\d{5}_.*_月报表'
    - '^\d{4}-\d{2}-\d{2}_\d{5}_.*_月報表'

    # 代表委任表格
    - '^\d{4}-\d{2}-\d{2}_\d{5}_.*_委任代表表格'

    # 展示文件
    - '^\d{4}-\d{2}-\d{2}_\d{5}_.*_展示文件'

    # 董事名单
    - '^\d{4}-\d{2}-\d{2}_\d{5}_.*_董事名单'

    # 各种更改
    - '^\d{4}-\d{2}-\d{2}_\d{5}_.*_更[换換改變]'

  # 白名单模式（匹配这些正则模式的文档会被优先处理）
  whitelist_patterns: []

  # 是否启用模式过滤
  enabled: true

# 文件属性过滤
file_filters:
  # 文件大小过滤（单位：字节）
  size:
    # 最小文件大小（小于此大小的文件会被跳过）
    min_size: 1024  # 1KB
    # 最大文件大小（大于此大小的文件会被跳过）
    max_size: 104857600  # 100MB
    enabled: false

  # 文件日期过滤
  date:
    # 最早可处理的文档日期（早于此日期的会被跳过）
    # 格式：YYYY-MM-DD
    earliest_date: null
    # 最晚可处理的文档日期（晚于此日期的会被跳过）
    latest_date: null
    enabled: false

  # 文件名长度过滤
  filename_length:
    # 最小长度
    min_length: 5
    # 最大长度
    max_length: 200
    enabled: false

# 特殊规则
special_rules:
  # 强制处理：如果文档匹配此规则，无论其他规则如何都会被处理
  force_process_patterns:
    - "非常重大收购"
    - "very_substantial_acquisition"

  # 强制跳过：如果文档匹配此规则，无论其他规则如何都会被跳过
  force_skip_patterns:
    - "内部资料"
    - "draft"

  # 是否启用特殊规则
  enabled: true

# 日志配置
logging:
  # 是否打印详细的过滤决策日志
  verbose: true
  # 是否记录每个文档的过滤决策
  log_decisions: true

# 缓存配置
cache:
  # 是否启用过滤结果缓存（基于文件路径和规则哈希）
  enabled: true
  # 缓存TTL（秒）
  ttl: 3600
